server:
  port: 9003
   

 
spring:
  application:
    name: springboot-crud-hibernate-example
  datasource: 
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect

# h2 database

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true


 # https://www.javaguides.net/2019/08/spring-boot-crud-rest-api-spring-data-jpa-h2-database-example.html
 # https://howtodoinjava.com/spring-data/spring-boot-with-mongodb/
